# Generated by Django 4.2.2 on 2023-08-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_feed_lang_alter_feed_pubdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="link",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="pubDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
